### ISSUE TITLE
Integration not found error

### ISSUE THREAD

**Issue by RamonBalthazar** [v6ak/v6-quietdrift#7]
I followed the README instructions and added the `v6_quietdrift:` line to `configuration.yaml`. After restarting I got the notification and logs below.
I am new to Home Assistant, is there an installation step missing from the README?

<img width="499" alt="image" src="https://github.com/v6ak/v6-quietdrift/assets/4910678/ea34f8e6-8985-4802-bf97-bb133c9805f8">

<img width="863" alt="image" src="https://github.com/v6ak/v6-quietdrift/assets/4910678/5a63cfe3-7519-4009-9cd4-3570298b80e1">

## My `configuration.yaml`
```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

v6_quietdrift:

#---Switchbot Speed Control
cover:
  - platform: template
    covers:
      livroom_backcurtain_custom:
        friendly_name: "Testing quiet curtain"
        position_template: "{{ state_attr('cover.livroom_backcurtain', 'current_position') }}"
        open_cover:
          service: cover.v6_set_switchbot_curtain_position
          data_template:
            speed: "{{ states('input_select.livroom_backcurtain_speed') | int }}"
            position: 100
            entity_id: cover.left_bedroom_curtain
        close_cover:
          service: cover.v6_set_switchbot_curtain_position
          data_template:
            speed: "{{ states('input_select.livroom_backcurtain_speed') | int }}"
            position: 0
            entity_id: cover.left_bedroom_curtain
        set_cover_position:
          service: cover.v6_set_switchbot_curtain_position
          data_template:
            position: "{{ position }}"
            speed: "{{ states('input_select.livroom_backcurtain_speed') | int }}"
            entity_id: cover.left_bedroom_curtain
```
